<?xml version="1.0" encoding="ASCII"?>
<Component:ComponentType xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:Component="com.mobile-devices.jcpn" fullname="com::test::sequences" name="sequences" version="1.00000" SDKVersion="3.1.0-20130911_core325_358">
  <initials href="Initials.inc#/"/>
  <provided href="Provided.inc#/"/>
  <required href="Required.inc#/"/>
  <parameters href="Parameters.inc#/"/>
  <dbvariables href="DbVariables.inc#/"/>
</Component:ComponentType>
