<?xml version="1.0" encoding="ASCII"?>
<Component:RequiredType xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:Component="com.mobile-devices.jcpn">
  <interface modifier="" name="Debug" pkg="com::mdi::tools::dbg"/>
  <interface modifier="" name="MessageGate" pkg="com::mdi::services::messageGate"/>
  <interface modifier="" name="BinaryGate" pkg="com::mdi::services::binaryGate"/>
</Component:RequiredType>
